
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build: 
    docker:
      - image: circleci/node:10.16.3
    environment:
      NODE_ENV: test
    steps:
      - checkout

      # Node caché
      - restore_cache:
          keys: 
            - node-v10-{{ checksum "package-lock.json" }}
            - node-v10-
      - run: npm install
      - save_cache:
          key: node-v10-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
            - node_modules
            - ~/.yarn
      - run: npm run test